---
cgit_url: https://80x24.org/mwrap.git
git_url: https://80x24.org/mwrap.git
rdoc_url: https://80x24.org/mwrap/
ml_url: https://80x24.org/mwrap-public/
public_email: mwrap-public@80x24.org
nntp_url:
  - nntp://news.public-inbox.org/inbox.comp.lang.ruby.mwrap
